AWSTemplateFormatVersion: '2010-09-09'
Description: Stack 3 - Balanceo y Escalabilidad Jorge - Miguel

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-Jorge-Miguel
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-Jorge-Miguel
      Subnets: !Ref Subnets
      SecurityGroups:
        - !ImportValue SG-ALB-Jorge-Miguel
      Type: application

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lt-Jorge-Miguel
      LaunchTemplateData:
        ImageId: ami-0cca150d127c2216f
        InstanceType: t3.micro
        SecurityGroupIds:
          - !ImportValue SG-ASG-Jorge-Miguel
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Hello World from $(hostname -f) - V2</h1>" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: asg-Jorge-Miguel
      VPCZoneIdentifier: !Ref Subnets
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '6'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref TargetGroup
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

  ASGWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MinSize: 1
      PoolState: Stopped

Outputs:
  ALBDNS:
    Description: DNS del Load Balancer
    Value: !GetAtt ALB.DNSName
  ASGName:
    Value: !Ref AutoScalingGroup
    Export:
      Name: ASGName-Jorge-Miguel
