AWSTemplateFormatVersion: '2010-09-09'
Description: Stack 2 - EC2 Estatica con Elastic IP creada desde GitHub Actions

Parameters:
  SecurityStackName:
    Type: String
    Default: SecurityGroups-Jorge-Miguel
    Description: Nombre del stack de seguridad para importar el Security Group

Resources:

  StaticEC2:
    Type: AWS::EC2::Instance
    Properties:
      # Eliminamos AvailabilityZone para que AWS elija la subred por defecto correcta automáticamente
      ImageId: ami-0cca150d127c2216f
      InstanceType: t3.micro
      SecurityGroupIds:
        - !ImportValue 
          Fn::Sub: '${SecurityStackName}-EC2SecurityGroupId'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Actualizar el sistema e instalar Apache (servidor web)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Instancia Estatica - Desplegado por Jorge y Miguel</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: EC2-Estatica-Jorge-Miguel

  # Elastic IP requerida por la rúbrica del parcial
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref StaticEC2
      Tags:
        - Key: Name
          Value: EIP-Jorge-Miguel

Outputs:

  InstanceId:
    Value: !Ref StaticEC2

  PublicIP:
    Description: IP estatica asignada mediante Elastic IP para probar en el navegador
    Value: !Ref MyElasticIP
