AWSTemplateFormatVersion: '2010-09-09'
Description: Stack Security Groups - Jorge-Miguel

Resources:

  # 1. Grupo de Seguridad para el ALB
  SGParaALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para Application Load Balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-ALB-Jorge-Miguel

  # 2. Grupo de Seguridad para las EC2
  SGParaEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para instancias EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-EC2-Jorge-Miguel

  # 3. Inyección de Regla Cruzada (Se usa !GetAtt para forzar estrictamente el formato sg-...)
  PermitirTraficoDelALBaEC2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt SGParaEC2.GroupId          # Destino: ID real sg-... de la EC2
      SourceSecurityGroupId: !GetAtt SGParaALB.GroupId  # Origen: ID real sg-... del ALB
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80

Outputs:

  SGEc2Id:
    Description: ID del Security Group de la EC2 para importar en otros stacks
    Value: !Ref SGParaEC2
    Export:
      Name: !Sub '${AWS::StackName}-EC2SecurityGroupId'

  SGAlbId:
    Description: ID del Security Group del ALB para importar en otros stacks
    Value: !Ref SGParaALB
    Export:
      Name: !Sub '${AWS::StackName}-ALBSecurityGroupId'
