AWSTemplateFormatVersion: '2010-09-09'
Description: Stack 3 - Balanceo y Escalabilidad (ALB + ASG + Warm Pool) - Jorge-Miguel

Parameters:
  SecurityStackName:
    Type: String
    Default: SecurityGroups-Jorge-Miguel

Resources:

  # 1. Application Load Balancer
  MyApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB-Jorge-Miguel
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !ImportValue 
          Fn::Sub: '${SecurityStackName}-ALBSecurityGroupId'
      # NOTA: Al omitir la propiedad "Subnets", AWS asocia automáticamente las subredes públicas por defecto de tu VPC.

  MyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyALBTargetGroup

  # 2. Target Group
  MyALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TG-Jorge-Miguel
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Port: 80
      Protocol: HTTP

  # 3. Launch Template (Estructura de tu plantilla base)
  MyServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LT-Jorge-Miguel
      LaunchTemplateData:
        ImageId: ami-0cca150d127c2216f
        InstanceType: t3.micro
        SecurityGroupIds:
          - !ImportValue 
            Fn::Sub: '${SecurityStackName}-EC2SecurityGroupId'
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>App Escalable - Version 1 - Jorge y Miguel</h1>" > /var/www/html/index.html

  # 4. Auto Scaling Group
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-Jorge-Miguel
      MinSize: '1'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref MyALBTargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref MyServerLaunchTemplate
        Version: '1'
      AvailabilityZones:
        - us-east-1a
        - us-east-1b # Distribuye automáticamente las instancias en las zonas por defecto de la región

  # 5. Warm Pool (Obligatorio en la rúbrica)
  MyWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      PoolState: Stopped
      MinSize: 1

Outputs:
  ALBDNSName:
    Description: DNS del Balanceador para probar la App en el navegador
    Value: !GetAtt MyApplicationLoadBalancer.DNSName
