name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  Destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Stack Automation
        run: |
          aws cloudformation delete-stack \
            --stack-name Automation-Jorge-Miguel
          aws cloudformation wait stack-delete-complete \
            --stack-name Automation-Jorge-Miguel

      - name: Destroy Stack ALB y ASG
        run: |
          aws cloudformation delete-stack \
            --stack-name ALB-ASG-Jorge-Miguel
          aws cloudformation wait stack-delete-complete \
            --stack-name ALB-ASG-Jorge-Miguel

      - name: Destroy Stack EC2 Estatica
        run: |
          aws cloudformation delete-stack \
            --stack-name EC2-Jorge-Miguel
          aws cloudformation wait stack-delete-complete \
            --stack-name EC2-Jorge-Miguel

      - name: Destroy Stack Security Groups
        run: |
          aws cloudformation delete-stack \
            --stack-name SecurityGroups-Jorge-Miguel
          aws cloudformation wait stack-delete-complete \
            --stack-name SecurityGroups-Jorge-Miguel
            